
version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - webnet

  backend:
    build: ./backend
    container_name: backend
    networks:
      - webnet

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
