# Basis-Image
FROM python:3.11-slim
# Arbeitsverzeichnis im Container erstellen
WORKDIR /app
# Abhängigkeiten installieren
COPY req.txt .

RUN pip install --no-cache-dir -r req.txt
# Anwendungscode kopieren           
COPY . .

# Container starten
CMD ["python", "app.py"]